// ============================================================================
// EyeNova Qatar - Complete Retail Catalog Data (EyeNova Qatar Luxury Optical)
// ============================================================================

export type MockProduct = {
  id: string;
  sku: string;
  productType: "COLORED_CONTACT_LENSES" | "MEDICAL_CONTACT_LENSES" | "LENS_SOLUTION_CARE" | "SPECTACLES" | "SUNGLASSES" | "LASHES_BEAUTY";
  titleEn: string;
  titleAr: string;
  slug: string;
  descriptionEn: string;
  descriptionAr: string;
  categorySlug: string;
  brandName: string;
  collectionName?: string;
  basePriceQar: number;
  salePriceQar?: number;
  stockQuantity: number;
  isFeatured: boolean;
  lensDuration?: string; // DAILY_DISPOSABLE, MONTHLY, 3_MONTHS, 6_MONTHS, YEARLY
  packSize?: number;
  baseCurve?: number;
  diameter?: number;
  waterContent?: number;
  colorNameEn?: string;
  colorNameAr?: string;
  colorHex?: string;
  availablePowers?: string[];
  lensWidth?: number;
  bridgeWidth?: number;
  templeLength?: number;
  tryOnModelUrl?: string;
  images: { imageUrl: string; isPrimary: boolean; isEyeShot?: boolean }[];
};

export const MOCK_PRODUCTS: MockProduct[] = [
  // --------------------------------------------------------------------------
  // 1. COLORED CONTACT LENSES (Bella, Lensme, Amara, Diva, FreshLook)
  // --------------------------------------------------------------------------
  {
    id: "p1",
    sku: "BEL-DIA-GRY-01",
    productType: "COLORED_CONTACT_LENSES",
    titleEn: "Bella Diamond Gray Shadow Contact Lenses",
    titleAr: "عدسات بيلا دايموند جراي شادو اللاصقة",
    slug: "bella-diamond-gray-shadow",
    descriptionEn: "Seductive gray shade with a soft limbal ring for an enchanting eye enlargement look.",
    descriptionAr: "درجة رمادية ساحرة مع تحديد ناعم لتوسيع شكل العين وإبراز جمالها الطبيعي.",
    categorySlug: "colored-lenses",
    brandName: "Bella",
    collectionName: "Bella Diamond",
    basePriceQar: 145.0,
    salePriceQar: 130.0,
    stockQuantity: 50,
    isFeatured: true,
    lensDuration: "3_MONTHS",
    packSize: 2,
    baseCurve: 8.6,
    diameter: 14.5,
    waterContent: 38.0,
    colorNameEn: "Gray Shadow",
    colorNameAr: "جراي شادو",
    colorHex: "#708090",
    availablePowers: ["0.00", "-0.50", "-0.75", "-1.00", "-1.25", "-1.50", "-1.75", "-2.00", "-2.25", "-2.50", "-2.75", "-3.00", "-3.50", "-4.00", "-4.50", "-5.00", "-6.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop", isPrimary: true, isEyeShot: true },
    ],
  },
  {
    id: "p2",
    sku: "BEL-ELT-SND-02",
    productType: "COLORED_CONTACT_LENSES",
    titleEn: "Bella Elite Sandy Brown Contact Lenses",
    titleAr: "عدسات بيلا ايليت ساندي براون اللاصقة",
    slug: "bella-elite-sandy-brown",
    descriptionEn: "Subtle blend of soft warm brown tones inspired by Arabian desert dunes.",
    descriptionAr: "مزيج ناعم من درجات البني الدافئ المستوحى من رمال الصحراء العربية.",
    categorySlug: "colored-lenses",
    brandName: "Bella",
    collectionName: "Bella Elite",
    basePriceQar: 150.0,
    salePriceQar: 135.0,
    stockQuantity: 45,
    isFeatured: true,
    lensDuration: "3_MONTHS",
    packSize: 2,
    baseCurve: 8.6,
    diameter: 14.5,
    waterContent: 38.0,
    colorNameEn: "Sandy Brown",
    colorNameAr: "ساندي براون",
    colorHex: "#B8860B",
    availablePowers: ["0.00", "-0.50", "-1.00", "-1.50", "-2.00", "-2.50", "-3.00", "-3.50", "-4.00", "-5.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop", isPrimary: true, isEyeShot: true },
    ],
  },
  {
    id: "p3",
    sku: "LNS-CAF-BRN-03",
    productType: "COLORED_CONTACT_LENSES",
    titleEn: "Lensme Caffe Natural Warm Brown Lenses",
    titleAr: "عدسات لينس مي كافيه بني دافئ طبيعي",
    slug: "lensme-caffe-brown",
    descriptionEn: "Warm coffee brown tone designed for dark Middle Eastern eyes with seamless blending.",
    descriptionAr: "درجة البني الدافئ كافيه المصممة خصيصاً للعيون العربية الداكنة.",
    categorySlug: "colored-lenses",
    brandName: "Lensme",
    collectionName: "Lensme Natural",
    basePriceQar: 160.0,
    salePriceQar: 145.0,
    stockQuantity: 40,
    isFeatured: true,
    lensDuration: "6_MONTHS",
    packSize: 2,
    baseCurve: 8.6,
    diameter: 14.2,
    waterContent: 38.0,
    colorNameEn: "Caffe Brown",
    colorNameAr: "كافيه بني",
    colorHex: "#6F4E37",
    availablePowers: ["0.00", "-0.50", "-0.75", "-1.00", "-1.50", "-2.00", "-2.50", "-3.00", "-3.50", "-4.00", "-5.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop", isPrimary: true, isEyeShot: true },
    ],
  },
  {
    id: "p4",
    sku: "LNS-CAR-04",
    productType: "COLORED_CONTACT_LENSES",
    titleEn: "Lensme Caramel Golden Hazel Lenses",
    titleAr: "عدسات لينس مي كراميل عسلي ذهبي",
    slug: "lensme-caramel",
    descriptionEn: "Top-selling radiant golden caramel shade that brightens deep eyes effortlessly.",
    descriptionAr: "اللون الكراميل الذهبي الأكثر مبيعاً الذي يمنح العيون إشراقة ساحرة.",
    categorySlug: "colored-lenses",
    brandName: "Lensme",
    collectionName: "Lensme Natural",
    basePriceQar: 160.0,
    salePriceQar: 145.0,
    stockQuantity: 60,
    isFeatured: true,
    lensDuration: "6_MONTHS",
    packSize: 2,
    baseCurve: 8.6,
    diameter: 14.2,
    waterContent: 38.0,
    colorNameEn: "Caramel",
    colorNameAr: "كراميل",
    colorHex: "#C68B59",
    availablePowers: ["0.00", "-0.50", "-1.00", "-1.50", "-2.00", "-2.50", "-3.00", "-3.50", "-4.00", "-5.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop", isPrimary: true, isEyeShot: true },
    ],
  },
  {
    id: "p5",
    sku: "AMR-TOF-HZL-05",
    productType: "COLORED_CONTACT_LENSES",
    titleEn: "Amara Toffee Hazel Contact Lenses",
    titleAr: "عدسات أمارا توفي عسلي لاصقة",
    slug: "amara-toffee-hazel",
    descriptionEn: "Rich caramel & honey hazel tone endorsed by Middle Eastern celebrity makeup artists.",
    descriptionAr: "درجة العسلي والكراميل الغنية المفضلة لدى أخصائيي المكياج في الخليج.",
    categorySlug: "colored-lenses",
    brandName: "Amara",
    collectionName: "Amara Celebrity",
    basePriceQar: 155.0,
    salePriceQar: 140.0,
    stockQuantity: 65,
    isFeatured: true,
    lensDuration: "MONTHLY",
    packSize: 2,
    baseCurve: 8.7,
    diameter: 14.5,
    waterContent: 38.0,
    colorNameEn: "Toffee Hazel",
    colorNameAr: "توفي عسلي",
    colorHex: "#D2691E",
    availablePowers: ["0.00", "-0.50", "-1.00", "-1.50", "-2.00", "-2.50", "-3.00", "-4.00", "-5.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&auto=format&fit=crop", isPrimary: true, isEyeShot: true },
    ],
  },
  {
    id: "p6",
    sku: "DIV-AMD-06",
    productType: "COLORED_CONTACT_LENSES",
    titleEn: "Diva Amande Natural Olive Brown Lenses",
    titleAr: "عدسات ديفا اماند زيتوني بني طبيعي",
    slug: "diva-amande",
    descriptionEn: "Elegant hazel-olive shade with high oxygen permeability for all-day comfort.",
    descriptionAr: "لون زيتوني عسلي أنيق مع نفاذية عالية للأكسجين لراحة تدوم طوال اليوم.",
    categorySlug: "colored-lenses",
    brandName: "Diva",
    collectionName: "Diva Natural",
    basePriceQar: 150.0,
    stockQuantity: 40,
    isFeatured: true,
    lensDuration: "MONTHLY",
    packSize: 2,
    baseCurve: 8.6,
    diameter: 14.5,
    waterContent: 43.0,
    colorNameEn: "Amande Olive",
    colorNameAr: "اماند",
    colorHex: "#808000",
    availablePowers: ["0.00", "-0.50", "-1.00", "-1.50", "-2.00", "-2.50", "-3.00", "-3.50", "-4.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&auto=format&fit=crop", isPrimary: true, isEyeShot: true },
    ],
  },

  // --------------------------------------------------------------------------
  // 2. CLEAR & MEDICAL CONTACT LENSES (Acuvue, Alcon, Biofinity)
  // --------------------------------------------------------------------------
  {
    id: "p7",
    sku: "ACU-MST-30PK",
    productType: "MEDICAL_CONTACT_LENSES",
    titleEn: "1 Day Acuvue Moist",
    titleAr: "عدسات 1-داي أكوفيو مويست الشفافة (30 عدسة)",
    slug: "1-day-acuvue-moist",
    descriptionEn: "LACREON technology keeps moisture locked in for 16 hours of daily wear comfort.",
    descriptionAr: "تقنية الترطيب الفائق الممتد طوال اليوم لحماية العين من الجفاف في طقس قطر الحار.",
    categorySlug: "medical-lenses",
    brandName: "Acuvue",
    collectionName: "1-Day Acuvue",
    basePriceQar: 159.0,
    stockQuantity: 120,
    isFeatured: true,
    lensDuration: "DAILY_DISPOSABLE",
    packSize: 30,
    baseCurve: 8.5,
    diameter: 14.2,
    waterContent: 58.0,
    availablePowers: ["-0.50", "-0.75", "-1.00", "-1.25", "-1.50", "-1.75", "-2.00", "-2.25", "-2.50", "-2.75", "-3.00", "-3.25", "-3.50", "-3.75", "-4.00", "-4.50", "-5.00", "-5.50", "-6.00", "-7.00", "-8.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&auto=format&fit=crop", isPrimary: true },
      { imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&auto=format&fit=crop", isPrimary: false },
      { imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&auto=format&fit=crop", isPrimary: false },
      { imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&auto=format&fit=crop", isPrimary: false },
    ],
  },
  {
    id: "p7_define_vivid",
    sku: "ACU-DEF-VIV-30PK",
    productType: "COLORED_CONTACT_LENSES",
    titleEn: "1 Day Acuvue Define Vivid Style",
    titleAr: "عدسات 1-داي أكوفيو ديفاين فيفيد ستايل (30 عدسة)",
    slug: "1-day-acuvue-define-vivid-style",
    descriptionEn: "Subtle limbal ring definition that enhances the natural beauty of dark eyes.",
    descriptionAr: "تحديد طبيعي يعزز إشراقة وتألق العيون مع حماية وترطيب فائق.",
    categorySlug: "colored-lenses",
    brandName: "Acuvue",
    collectionName: "Acuvue Define",
    basePriceQar: 215.0,
    stockQuantity: 50,
    isFeatured: true,
    lensDuration: "DAILY_DISPOSABLE",
    packSize: 30,
    baseCurve: 8.5,
    diameter: 14.2,
    waterContent: 58.0,
    availablePowers: ["0.00", "-0.50", "-1.00", "-1.50", "-2.00", "-2.50", "-3.00", "-3.50", "-4.00", "-5.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
  {
    id: "p7_moist_90pk",
    sku: "ACU-MST-90PK",
    productType: "MEDICAL_CONTACT_LENSES",
    titleEn: "1 Day Acuvue Moist 90 Pack",
    titleAr: "عدسات 1-داي أكوفيو مويست الشفافة (90 عدسة)",
    slug: "1-day-acuvue-moist-90-pack",
    descriptionEn: "Quarterly value pack with 90 daily disposable contact lenses with LACREON technology.",
    descriptionAr: "عبوة التوفير الفصلية تحتوي على 90 عدسة يومية أصلية بتقنية الترطيب المتقدمة.",
    categorySlug: "medical-lenses",
    brandName: "Acuvue",
    collectionName: "1-Day Acuvue",
    basePriceQar: 428.0,
    stockQuantity: 40,
    isFeatured: true,
    lensDuration: "DAILY_DISPOSABLE",
    packSize: 90,
    baseCurve: 8.5,
    diameter: 14.2,
    waterContent: 58.0,
    availablePowers: ["-1.00", "-1.50", "-2.00", "-2.50", "-3.00", "-3.50", "-4.00", "-4.50", "-5.00", "-5.50", "-6.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
  {
    id: "p7_moist_astigmatism",
    sku: "ACU-MST-AST-30PK",
    productType: "MEDICAL_CONTACT_LENSES",
    titleEn: "1 Day Acuvue Moist for Astigmatism",
    titleAr: "عدسات 1-داي أكوفيو مويست للاستجماتيزم (30 عدسة)",
    slug: "1-day-acuvue-moist-for-astigmatism",
    descriptionEn: "Blink stabilized design providing crisp, steady vision for people with astigmatism.",
    descriptionAr: "تصميم ثابت مع الرمش يمنحك رؤية حادة ومستقرة طوال اليوم لمرضى الاستجماتيزم.",
    categorySlug: "medical-lenses",
    brandName: "Acuvue",
    collectionName: "1-Day Acuvue",
    basePriceQar: 230.0,
    stockQuantity: 45,
    isFeatured: true,
    lensDuration: "DAILY_DISPOSABLE",
    packSize: 30,
    baseCurve: 8.5,
    diameter: 14.5,
    waterContent: 58.0,
    availablePowers: ["-0.75", "-1.00", "-1.50", "-2.00", "-2.50", "-3.00", "-3.50", "-4.00", "-4.50", "-5.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
  {
    id: "p8",
    sku: "ACU-OAS-HYD-30PK",
    productType: "MEDICAL_CONTACT_LENSES",
    titleEn: "Acuvue Oasys 1 DAY with HydraLuxe",
    titleAr: "عدسات أكوفيو أواسيس 1-داي مع هيدرالوكس (30 عدسة)",
    slug: "acuvue-oasys-1-day-hydraluxe",
    descriptionEn: "Tear-infused design mimicking your natural tear film for demanding digital screen use.",
    descriptionAr: "تصميم متكامل مع الدموع الطبيعية لتقليل إجهاد العين أمام الشاشات الرقمية.",
    categorySlug: "medical-lenses",
    brandName: "Acuvue",
    collectionName: "Acuvue Oasys",
    basePriceQar: 195.0,
    stockQuantity: 95,
    isFeatured: true,
    lensDuration: "DAILY_DISPOSABLE",
    packSize: 30,
    baseCurve: 8.5,
    diameter: 14.3,
    waterContent: 38.0,
    availablePowers: ["-0.50", "-0.75", "-1.00", "-1.50", "-2.00", "-2.50", "-3.00", "-3.50", "-4.00", "-4.50", "-5.00", "-6.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
  {
    id: "p9",
    sku: "ALC-DT1-30PK",
    productType: "MEDICAL_CONTACT_LENSES",
    titleEn: "Dailies Total 1",
    titleAr: "عدسات ألكون ديليز توتال 1 ذات التدرج المائي (30 عدسة)",
    slug: "alcon-dailies-total-1",
    descriptionEn: "Water gradient technology providing nearly 100% water at the outermost surface.",
    descriptionAr: "تقنية التدرج المائي التي تقترب من 100% ماء على السطح الخارجي للعدسة.",
    categorySlug: "medical-lenses",
    brandName: "Alcon",
    collectionName: "Dailies Total 1",
    basePriceQar: 225.0,
    stockQuantity: 70,
    isFeatured: true,
    lensDuration: "DAILY_DISPOSABLE",
    packSize: 30,
    baseCurve: 8.5,
    diameter: 14.1,
    waterContent: 33.0,
    availablePowers: ["-0.50", "-1.00", "-1.50", "-2.00", "-2.50", "-3.00", "-3.50", "-4.00", "-5.00", "-6.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
  {
    id: "p9_aquacomfort",
    sku: "ALC-DAC-30PK",
    productType: "MEDICAL_CONTACT_LENSES",
    titleEn: "Dailies AquaComfort Plus",
    titleAr: "عدسات ديليز أكوا كومفورت بلس (30 عدسة)",
    slug: "dailies-aquacomfort-plus",
    descriptionEn: "Blink-activated moisture technology for refreshing comfort throughout the day.",
    descriptionAr: "تقنية الترطيب المفعلة مع الرمش لراحة مستمرة ومنعشة طوال اليوم.",
    categorySlug: "medical-lenses",
    brandName: "Alcon",
    collectionName: "Dailies",
    basePriceQar: 175.0,
    stockQuantity: 80,
    isFeatured: true,
    lensDuration: "DAILY_DISPOSABLE",
    packSize: 30,
    baseCurve: 8.7,
    diameter: 14.0,
    waterContent: 69.0,
    availablePowers: ["-0.50", "-0.75", "-1.00", "-1.25", "-1.50", "-1.75", "-2.00", "-2.25", "-2.50", "-3.00", "-3.50", "-4.00", "-4.50", "-5.00", "-5.50", "-6.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
  {
    id: "p9_airoptix",
    sku: "ALC-AOPT-6PK",
    productType: "MEDICAL_CONTACT_LENSES",
    titleEn: "Air Optix plus HydraGlyde 6 pack",
    titleAr: "عدسات إير أوبتكس بلس هايدراجلايد (6 عدسات)",
    slug: "air-optix-plus-hydraglyde-6-pack",
    descriptionEn: "SmartShield Technology for excellent lipid deposit resistance and HydraGlyde Moisture Matrix.",
    descriptionAr: "تقنية سمارت شيلد لمقاومة الرواسب مع مصفوفة ترطيب هايدراجلايد لراحة شهرية استثنائية.",
    categorySlug: "medical-lenses",
    brandName: "Alcon",
    collectionName: "Air Optix",
    basePriceQar: 220.0,
    stockQuantity: 90,
    isFeatured: true,
    lensDuration: "MONTHLY",
    packSize: 6,
    baseCurve: 8.6,
    diameter: 14.2,
    waterContent: 33.0,
    availablePowers: ["-0.50", "-0.75", "-1.00", "-1.25", "-1.50", "-1.75", "-2.00", "-2.25", "-2.50", "-3.00", "-3.50", "-4.00", "-4.50", "-5.00", "-5.50", "-6.00", "-6.50", "-7.00", "-8.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
  {
    id: "p10",
    sku: "BIO-MTH-6PK",
    productType: "MEDICAL_CONTACT_LENSES",
    titleEn: "Biofinity Monthly Clear Contact Lenses (6 Lenses / Box)",
    titleAr: "عدسات بايو فينيتي الشهرية الشفافة (6 عدسات في العلبة)",
    slug: "biofinity-monthly-6-pack",
    descriptionEn: "Aquaform technology delivers high oxygen transmission for crisp monthly wear.",
    descriptionAr: "تقنية أكوا فورم لنفاذية أكسجين فائقة وراحة استثنائية طوال الشهر.",
    categorySlug: "medical-lenses",
    brandName: "CooperVision",
    collectionName: "Biofinity",
    basePriceQar: 175.0,
    stockQuantity: 85,
    isFeatured: true,
    lensDuration: "MONTHLY",
    packSize: 6,
    baseCurve: 8.6,
    diameter: 14.0,
    waterContent: 48.0,
    availablePowers: ["-0.50", "-0.75", "-1.00", "-1.25", "-1.50", "-2.00", "-2.50", "-3.00", "-3.50", "-4.00", "-4.50", "-5.00", "-6.00", "-7.00"],
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },

  // --------------------------------------------------------------------------
  // 3. SOLUTIONS & EYE DROPS (Opti-Free, Biotrue, Systane, Refresh)
  // --------------------------------------------------------------------------
  {
    id: "p11",
    sku: "OPT-PUR-300ML",
    productType: "LENS_SOLUTION_CARE",
    titleEn: "Opti-Free PureMoist Multi-Purpose Solution (300ml)",
    titleAr: "محلول أوبتي فري بيور مويست لتعقيم العدسات (300 مل)",
    slug: "opti-free-puremoist-300ml",
    descriptionEn: "HydraGlyde Moisture Matrix creates a continuous shield of moisture for soft contact lenses.",
    descriptionAr: "محلول التعقيم الشامل الذي يوفر غلاف ترطيب مستمر للعدسات طوال اليوم.",
    categorySlug: "solutions-drops",
    brandName: "Alcon",
    basePriceQar: 45.0,
    stockQuantity: 150,
    isFeatured: true,
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
  {
    id: "p12",
    sku: "BIO-SOL-300ML",
    productType: "LENS_SOLUTION_CARE",
    titleEn: "Biotrue Multi-Purpose Solution for Soft Lenses (300ml)",
    titleAr: "محلول بايوترو متعدد الاستخدامات للعدسات اللاصقة (300 مل)",
    slug: "biotrue-multi-purpose-solution",
    descriptionEn: "Formulated to match the pH of healthy tears with natural lubricants found in the eye.",
    descriptionAr: "محلول متوازن مع حموضة الدموع الطبيعية لتعقيم فائق بدون أي تهيج للعين.",
    categorySlug: "solutions-drops",
    brandName: "Bausch & Lomb",
    basePriceQar: 50.0,
    stockQuantity: 90,
    isFeatured: true,
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
  {
    id: "p13",
    sku: "SYS-ULT-10ML",
    productType: "LENS_SOLUTION_CARE",
    titleEn: "Systane Ultra Lubricant Eye Drops (10ml)",
    titleAr: "قطرة سيستان الترا المرطبة للعين المجهدة (10 مل)",
    slug: "systane-ultra-eye-drops",
    descriptionEn: "Instant relief from burning and irritation caused by dry eye syndrome and contact lenses.",
    descriptionAr: "ترطيب فوري وحماية متقدمة من جفاف العين والإجهاد الناتج عن ارتداء العدسات.",
    categorySlug: "solutions-drops",
    brandName: "Alcon",
    basePriceQar: 40.0,
    stockQuantity: 110,
    isFeatured: true,
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
  {
    id: "p14",
    sku: "REF-PLS-30VL",
    productType: "LENS_SOLUTION_CARE",
    titleEn: "Refresh Plus Preservative-Free Lubricant Drops (30 Vials)",
    titleAr: "قطرات ريفريش بلس الخالية من المواد الحافظة (30 أمبولة)",
    slug: "refresh-plus-lubricant-drops",
    descriptionEn: "Single-use preservative-free vials safe to use directly with contact lenses.",
    descriptionAr: "أمبولات استخدام فردي خالية من المواد الحافظة آمنة تماماً مع العدسات اللاصقة.",
    categorySlug: "solutions-drops",
    brandName: "Allergan",
    basePriceQar: 48.0,
    stockQuantity: 80,
    isFeatured: true,
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },

  // --------------------------------------------------------------------------
  // 4. SPECTACLES & GLASSES (Pure Titanium, TR90, Blue Shield)
  // --------------------------------------------------------------------------
  {
    id: "p15",
    sku: "EYE-TIT-BLK-15",
    productType: "SPECTACLES",
    titleEn: "EyeNova Pure Titanium Ultra-Light Frame",
    titleAr: "إطار عين نوفا تيتانيوم نقي فائق الخفة",
    slug: "eyenova-pure-titanium-black",
    descriptionEn: "Japanese pure titanium frame weighing only 14 grams. Corrosion resistant & hypoallergenic.",
    descriptionAr: "إطار تيتانيوم نقي ياباني بوزن 14 جرام فقط. مقاوم للتآكل ولطيف على البشرة.",
    categorySlug: "eyeglasses",
    brandName: "EyeNova",
    basePriceQar: 350.0,
    salePriceQar: 295.0,
    stockQuantity: 25,
    isFeatured: true,
    lensWidth: 52.0,
    bridgeWidth: 18.0,
    templeLength: 140.0,
    tryOnModelUrl: "/models/frame-black.png",
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
  {
    id: "p16",
    sku: "EYE-TR90-BLU-16",
    productType: "SPECTACLES",
    titleEn: "EyeNova TR90 Flexible Frame with Blue Light Shield",
    titleAr: "إطار تي آر 90 مرن مع حماية من الضوء الأزرق",
    slug: "eyenova-tr90-blue-shield",
    descriptionEn: "Flexible featherlight Swiss TR90 material with UV420 Blue Light Shield lenses included.",
    descriptionAr: "مادة سويسرية مرنة وخفيفة الوزن مزودة بعدسات حماية متقدمة من أشعة الشاشات الزرقاء.",
    categorySlug: "eyeglasses",
    brandName: "EyeNova",
    basePriceQar: 220.0,
    salePriceQar: 185.0,
    stockQuantity: 35,
    isFeatured: true,
    lensWidth: 50.0,
    bridgeWidth: 19.0,
    templeLength: 142.0,
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1591076482161-42ce6da69f67?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },

  // --------------------------------------------------------------------------
  // 5. SUNGLASSES
  // --------------------------------------------------------------------------
  {
    id: "p17",
    sku: "SUN-AVI-POL-17",
    productType: "SUNGLASSES",
    titleEn: "EyeNova Polarized Luxury Aviator Sunglasses",
    titleAr: "نظارة شمسية أفياتور مستقطبة فاخرة من عين نوفا",
    slug: "eyenova-polarized-aviator-sunglasses",
    descriptionEn: "Classic teardrop gold-tone metal frame with HD polarized UV400 glare protection.",
    descriptionAr: "إطار معدني ذهبي كلاسيكي مع عدسات مستقطبة عالية الدقة لحجب وهج الشمس.",
    categorySlug: "sunglasses",
    brandName: "EyeNova",
    basePriceQar: 280.0,
    salePriceQar: 240.0,
    stockQuantity: 30,
    isFeatured: true,
    lensWidth: 58.0,
    bridgeWidth: 14.0,
    templeLength: 145.0,
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },

  // --------------------------------------------------------------------------
  // 6. LASHES & ACCESSORIES
  // --------------------------------------------------------------------------
  {
    id: "p18",
    sku: "LSH-DOH-01",
    productType: "LASHES_BEAUTY",
    titleEn: "EyeNova Luxury 3D Silk Lashes - Doha Glow",
    titleAr: "رموش حريرية فاخرة ثلاثية الأبعاد - دوحة جلو",
    slug: "eyenova-silk-lashes-doha-glow",
    descriptionEn: "Handcrafted cruelty-free faux mink lashes with a flexible invisible cotton band.",
    descriptionAr: "رموش حريرية ثلاثية الأبعاد مصنعة يدوياً بشريط قطني مرن غير مرئي لراحة تامة.",
    categorySlug: "lashes",
    brandName: "EyeNova",
    basePriceQar: 65.0,
    stockQuantity: 75,
    isFeatured: true,
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1583001931096-959e9a1a6223?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
  {
    id: "p19",
    sku: "KIT-TRV-ACC-19",
    productType: "LENS_SOLUTION_CARE",
    titleEn: "Compact Contact Lens Travel Kit with Inbuilt Mirror & Tweezers",
    titleAr: "حقيبة سفر صغيرة للعدسات مع مرآة وملقط مخصص",
    slug: "compact-contact-lens-travel-kit",
    descriptionEn: "Hygiene travel companion containing solution vial, tweezer, insertion wand & dual case.",
    descriptionAr: "طقم سفر مدمج وأنيق يحتوي على علبة عدسات، قارورة محلول، ملقط، وأداة وضع العدسات مع مرآة.",
    categorySlug: "solutions-drops",
    brandName: "EyeNova",
    basePriceQar: 25.0,
    stockQuantity: 120,
    isFeatured: true,
    images: [
      { imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop", isPrimary: true },
    ],
  },
];
